### ISSUE TITLE
Snapshot of video failed to load for camera configuration 

### ISSUE THREAD

**Issue by lmatechuk** [localdevices/OpenRiverCam#102]
This issue occurred when completing camera configuration step 2 and 3. The snapshot of my video failed to load to the page, so I was unable to select the GCPs and the water level points. 

Link to image of issue
![image](https://user-images.githubusercontent.com/60800963/185999868-3eac2cf5-60cd-4a02-80cd-85e7c305384e.png)

link to video
[https://drive.google.com/file/d/1isZ0Mju2YMrYJuYlQ3nt2ql3h1tCPk1H/view?usp=sharing](url)

**Comment by hcwinsemius** [comment]
Did you use release 0.1? A regression in OpenCV causes that release to be broken. I just released 0.2.0 which resolves that.

**Comment by lmatechuk** [comment]
Great, thank you!
