### ISSUE TITLE
module 'cv2' has no attribute 'cv2'

### ISSUE THREAD

**Issue by the-nerdling** [localdevices/OpenRiverCam#94]
I'm getting this under movies>details

MOVIE_STATUS_ERROR
module 'cv2' has no attribute 'cv2'

I've tried installing opencv

**Comment by hcwinsemius** [comment]
Can you let us know what you did to receive this error? 

We currently recommend to only use OpenRiverCam directly checked out from github. Our first release is broken and we need significant updates in order to use our latest backend API. The latest code base should work.

**Comment by sir-bro-dude-guy** [comment]
`OpenRiverCam - main - ERROR - extract_frames failed with error module 'cv2' has no attribute 'cv2'`

During Setup > Camera Config > Time Span > control_points.mkv > Save

Broken link icon where we should expect the control point image to appear.
![image](https://user-images.githubusercontent.com/56481392/176251317-bc8d7b44-7be9-4058-bb64-9ee291155750.png)

**Comment by the-nerdling** [comment]
I was using the files from the releases tab.

I was adding a movie and in the cmd window i was getting "extract_frames failed with error module 'cv2' has no attribute 'cv2'"

I'm doing a fresh setup now using the -master folder

**Comment by hcwinsemius** [comment]
Please try the master branch. If that also does not work then I will look into it tomorrow.

**Comment by hcwinsemius** [comment]
I will look into this bug but cannot at the moment. I am out of office until 1st of August. I'll investigate after that.

**Comment by Sh1ken** [comment]
Thank you. Looking forward to it!

**Comment by hcwinsemius** [comment]
...and apologies for not checking earlier. Probably there is some change in the cv2 library that regressed into the openrivercam library. Our entirely revamped pyopenrivercam follow up library now has a proper test environment that should flag such problems. This new library is not in the front end yet but worth to try if you are not looking for a front end but merely for the functionalities. Please check https://localdevices.github.io/pyorc for more information.

**Comment by Sh1ken** [comment]
Is there a ETA for the fix, @hcwinsemius? Just asking because I don't know how serious/breaking the changes done to the cv2 library are. If you think that is probably not that bad, maybe I can even fix it myself.

**Comment by hcwinsemius** [comment]
We are working on it. We hopefully have a fix with the new API tomorrow.

**Comment by hcwinsemius** [comment]
Just an update: this issue is fixed but requires a few updates in the pyOpenRiverCam API. These are currently subject to testing and review. After release we will make a pull request and merge to resolve this issue.

**Comment by Sh1ken** [comment]
Thanks for the heads up. Looking forward to the final update!

**Comment by hcwinsemius** [comment]
This issue is now fixed. Can you try to reinstall the entire docker composition with

```
docker-compose build --no-cache
```
After this, you should be able to restart the service with:
```
docker-compose up
```
And then browse to http://localhost:9003
